import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.amazon.search.useQuery("tv");
  hello && console.log("🚀 ~ hello", hello.data);

  return (
    <>
      <Head>
        <title>Amazon Tools</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello</main>
    </>
  );
};

export default Home;
