import { Container, Tabs, Title } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import Search from "../components/Search";
import { api } from "../utils/api";

const Home: NextPage = () => {
  api.amazon.init.useQuery();

  return (
    <>
      <Head>
        <title>Amazon Tools</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container pt={25}>
        <Title align="center">Amazon Tools</Title>

        <Tabs defaultValue="search">
          <Tabs.List>
            <Tabs.Tab value="search">Keyword Search</Tabs.Tab>
            <Tabs.Tab value="product">Product Info</Tabs.Tab>
          </Tabs.List>

          <Tabs.Panel value="search" pt="sm">
            <Search />
          </Tabs.Panel>
        </Tabs>
      </Container>
    </>
  );
};

export default Home;
